# Generated by Django 4.1.7 on 2023-03-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0002_editora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editora',
        ),
    ]
